import { mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

import { buildDemoReleaseManifest } from '../../apps/web-control/src/lib/releaseManifest'
import { createDefaultPlaylistConfig } from '../../apps/web-control/src/lib/playlistConfig'
import type { SupabasePlaylistSnapshot } from '../../apps/web-control/src/lib/supabasePlaylistRepository'

const RELEASE_VERSION = 'DEMO-08-2026-R2'
const PARENT_RELEASE_VERSION = 'DEMO-08-2026-R1'
const UPDATED_AT = '2026-07-25T08:00:00.000Z'

const config = {
  ...createDefaultPlaylistConfig(),
  updatedAt: UPDATED_AT,
}

const snapshot = {
  id: 'seed-demo-08-2026',
  name: config.name,
  scope: 'all',
  branchId: null,
  status: 'draft',
  createdBy: null,
  createdAt: UPDATED_AT,
  updatedAt: UPDATED_AT,
  config,
  slides: config.items.map((slide, position) => ({
    playlistItemId: `seed-item-${position + 1}`,
    contentItemId: null,
    boardRowId: null,
    position,
    slide,
    media: {},
  })),
} satisfies SupabasePlaylistSnapshot

const manifest = buildDemoReleaseManifest(snapshot, RELEASE_VERSION)

const jsonbLiteral = (value: unknown) =>
  `'${JSON.stringify(value).replaceAll("'", "''")}'::jsonb`

const sql = `-- Generated by supabase/scripts/build-demo-cloud-seed.ts
-- Seeds the editable August demo playlist and publishes its immutable manifest.
-- Reruns preserve Admin edits, delivery progress and any newer desired release.

do $seed$
declare
  v_config jsonb := ${jsonbLiteral(config)};
  v_manifest jsonb := ${jsonbLiteral(manifest)};
  v_admin_id uuid;
  v_user_count integer;
  v_playlist_id uuid;
  v_playlist_count integer;
  v_existing_slide_count integer;
  v_seed_slides boolean := false;
  v_release_id uuid;
  v_release_status text;
  v_existing_manifest jsonb;
  v_parent_release_id uuid;
  v_target_screen_count integer;
  v_slide jsonb;
  v_content_id uuid;
  v_board_id uuid;
  v_board_code text;
  v_position integer := 0;
begin
  perform pg_advisory_xact_lock(hashtext('unite-vinhdanh-demo-08-2026-r2'));

  select count(*) into v_user_count from auth.users;
  if v_user_count <> 1 then
    raise exception 'Safety stop: expected exactly 1 auth user, found %', v_user_count;
  end if;
  select id into v_admin_id from auth.users limit 1;

  if not exists (
    select 1
    from public.vinhdanh_profiles
    where id = v_admin_id and role = 'super_admin'
  ) then
    raise exception 'Safety stop: the sole auth user is not super_admin';
  end if;

  select count(*) into v_target_screen_count
  from public.screens
  where is_active = true
    and screen_code in (
      'CN01-TV01', 'CN02-TV01', 'CN03-TV01',
      'CN04-TV01', 'CN05-TV01', 'CN06-TV01',
      'CN07-TV01', 'CN08-TV01', 'CN09-TV01'
    );
  if v_target_screen_count <> 9 then
    raise exception 'Safety stop: expected 9 active CN01-TV01..CN09-TV01 screens, found %',
      v_target_screen_count;
  end if;

  select count(*) into v_playlist_count
  from public.playlists
  where name = v_config->>'name' and status = 'draft';
  if v_playlist_count > 1 then
    raise exception 'Safety stop: multiple draft playlists have the same name';
  end if;

  select id into v_playlist_id
  from public.playlists
  where name = v_config->>'name' and status = 'draft'
  limit 1;

  if v_playlist_id is null then
    insert into public.playlists (id, name, scope, branch_id, status, created_by)
    values (
      'de080000-2026-4000-8000-000000000001',
      v_config->>'name',
      'all',
      null,
      'draft',
      v_admin_id
    )
    returning id into v_playlist_id;
    v_seed_slides := true;
  else
    select count(*) into v_existing_slide_count
    from public.playlist_items
    where playlist_id = v_playlist_id;
    if v_existing_slide_count = 0 then
      v_seed_slides := true;
    elsif v_existing_slide_count <> 12 then
      raise exception 'Safety stop: existing demo draft has % slides, expected 12',
        v_existing_slide_count;
    end if;
  end if;

  if v_seed_slides then
    delete from public.content_items
    where id in (
      select content_item_id
      from public.playlist_items
      where playlist_id = v_playlist_id and content_item_id is not null
    );
    delete from public.playlist_items where playlist_id = v_playlist_id;

    for v_slide in
      select value from jsonb_array_elements(v_config->'items')
    loop
      insert into public.content_items (
      content_type,
      title,
      body,
      duration_seconds,
      audio_enabled,
      priority,
      metadata,
      created_by
    )
    values (
      case v_slide->>'kind'
        when 'recognition' then 'recognition'
        when 'video' then 'video'
        when 'event' then 'event'
        else 'announcement'
      end,
      coalesce(nullif(v_slide->>'headline', ''), v_slide->>'title'),
      nullif(v_slide->>'body', ''),
      greatest(1, round((v_slide->>'duration')::numeric)::integer),
      coalesce((v_slide->>'audioEnabled')::boolean, false),
      v_position,
      jsonb_build_object(
        'repositorySchema', 'unite-vinhdanh-playlist-slide',
        'localItemId', v_slide->>'id',
        'subtitle', coalesce(v_slide->>'subtitle', '')
      ),
      v_admin_id
      )
      returning id into v_content_id;

      v_board_code := case v_slide->>'boardId'
      when 'manager-thong-soai' then 'QLCN_THONG_SOAI'
      when 'manager-dai-tuong' then 'QLCN_DAI_TUONG'
      when 'manager-thu-linh' then 'QLCN_THU_LINH'
      when 'leader-ky-lan' then 'LEADER_KY_LAN'
      when 'leader-phuong-hoang' then 'LEADER_PHUONG_HOANG'
      when 'leader-su-tu' then 'LEADER_SU_TU'
      when 'sale-fulltime' then 'SALE_FULL_TIME'
      when 'sale-parttime' then 'SALE_PART_TIME'
      when 'team-ranking' then 'TEAM_RANKING'
      else null
      end;
      v_board_id := null;
      if v_board_code is not null then
        select id into v_board_id
        from public.award_boards
        where code = v_board_code;
        if v_board_id is null then
          raise exception 'Award board % was not found', v_board_code;
        end if;
      end if;

      insert into public.playlist_items (
      playlist_id,
      content_item_id,
      board_id,
      position,
      duration_seconds,
      config
    )
    values (
      v_playlist_id,
      v_content_id,
      v_board_id,
      v_position,
      greatest(1, round((v_slide->>'duration')::numeric)::integer),
      jsonb_build_object(
        'schema', 'unite-vinhdanh-playlist-slide',
        'schemaVersion', 1,
        'playlist', jsonb_build_object(
          'version', 1,
          'schedule', v_config->'schedule',
          'repeat', v_config->'repeat',
          'updatedAt', v_config->>'updatedAt'
        ),
        'slide', v_slide,
        'media', '{}'::jsonb
      )
      );
      v_position := v_position + 1;
    end loop;
  else
    v_position := v_existing_slide_count;
  end if;

  update public.playlist_items pi
  set config = jsonb_set(
    pi.config,
    '{slide,mediaUrl}',
    to_jsonb((
      select item->>'mediaUrl'
      from jsonb_array_elements(v_config->'items') item
      where item->>'id' = 'pl-10'
    )),
    true
  )
  where pi.playlist_id = v_playlist_id
    and pi.config->'slide'->>'id' = 'pl-10'
    and coalesce(pi.config->'slide'->>'mediaUrl', '') = '';

  select id into v_parent_release_id
  from public.releases
  where release_version = '${PARENT_RELEASE_VERSION}';

  select id, status, manifest
  into v_release_id, v_release_status, v_existing_manifest
  from public.releases
  where release_version = '${RELEASE_VERSION}';

  if v_release_id is null then
    insert into public.releases (
      id,
      release_version,
      period_id,
      playlist_id,
      parent_release_id,
      status,
      activate_at,
      manifest,
      target_config,
      created_by,
      published_by,
      published_at
    )
    values (
      'de080000-2026-4000-8000-000000000003',
      '${RELEASE_VERSION}',
      '2026-08',
      v_playlist_id,
      v_parent_release_id,
      'published',
      now(),
      v_manifest,
      '{"scope":"all"}'::jsonb,
      v_admin_id,
      v_admin_id,
      now()
    )
    returning id into v_release_id;
  elsif v_release_status = 'published' then
    if v_existing_manifest is distinct from v_manifest then
      raise exception 'Safety stop: published release ${RELEASE_VERSION} has a different manifest';
    end if;
  else
    update public.releases
    set period_id = '2026-08',
        playlist_id = v_playlist_id,
        parent_release_id = v_parent_release_id,
        status = 'published',
        activate_at = now(),
        manifest = v_manifest,
        target_config = '{"scope":"all"}'::jsonb,
        created_by = coalesce(created_by, v_admin_id),
        published_by = v_admin_id,
        published_at = now()
    where id = v_release_id;
  end if;

  insert into public.release_targets (release_id, screen_id, delivery_status)
  select v_release_id, id, 'pending'
  from public.screens
  where is_active = true
    and screen_code in (
      'CN01-TV01', 'CN02-TV01', 'CN03-TV01',
      'CN04-TV01', 'CN05-TV01', 'CN06-TV01',
      'CN07-TV01', 'CN08-TV01', 'CN09-TV01'
    )
  on conflict (release_id, screen_id) do nothing;

  insert into public.screen_state (screen_id, desired_release_id, connection_state)
  select id, v_release_id, 'offline'
  from public.screens
  where is_active = true
    and screen_code in (
      'CN01-TV01', 'CN02-TV01', 'CN03-TV01',
      'CN04-TV01', 'CN05-TV01', 'CN06-TV01',
      'CN07-TV01', 'CN08-TV01', 'CN09-TV01'
    )
  on conflict (screen_id) do update
    set desired_release_id = excluded.desired_release_id
    where public.screen_state.desired_release_id is null
       or public.screen_state.desired_release_id = excluded.desired_release_id
       or public.screen_state.desired_release_id = v_parent_release_id;

  update public.releases
  set status = 'superseded'
  where id = v_parent_release_id
    and id <> v_release_id
    and status = 'published';

  insert into public.audit_logs (
    actor_id,
    action,
    entity_type,
    entity_id,
    after_data
  )
  select
    v_admin_id,
    'demo.seed',
    'release',
    v_release_id::text,
    jsonb_build_object(
      'releaseVersion', '${RELEASE_VERSION}',
      'periodId', '2026-08',
      'playlistId', v_playlist_id,
      'slideCount', v_position,
      'targetCount', (select count(*) from public.screens where is_active = true)
    )
  where not exists (
    select 1
    from public.audit_logs
    where action = 'demo.seed'
      and entity_type = 'release'
      and entity_id = v_release_id::text
  );
end
$seed$;

select
  (select count(*) from public.playlists where name = 'Chu kỳ vinh danh toàn hệ thống' and status = 'draft') as demo_playlists,
  (select count(*) from public.playlist_items pi join public.playlists p on p.id = pi.playlist_id where p.name = 'Chu kỳ vinh danh toàn hệ thống' and p.status = 'draft') as demo_slides,
  (select count(*) from public.releases where release_version = '${RELEASE_VERSION}' and status = 'published') as published_releases,
  (select count(*) from public.release_targets rt join public.releases r on r.id = rt.release_id where r.release_version = '${RELEASE_VERSION}') as release_targets,
  (select count(*) from public.screen_state ss join public.releases r on r.id = ss.desired_release_id where r.release_version = '${RELEASE_VERSION}') as desired_screens;
`

const outputPath = resolve(
  process.cwd(),
  'supabase',
  'generated',
  '20260725_seed_demo_cloud.sql',
)

const main = async () => {
  await mkdir(resolve(process.cwd(), 'supabase', 'generated'), { recursive: true })
  await writeFile(outputPath, sql, 'utf8')
  console.log(outputPath)
}

void main()
